### ISSUE TITLE
generate_sub_images in data.py

### ISSUE THREAD

**Issue by normalworld** [qobilidop/srcnn#11]
Thank you for your contributions.I can only find the function of generate_sub_images,but I can't find the reverse function when the program output the picture named output_image.Can you help me?

**Comment by qobilidop** [comment]
It's been a long time and I don't have a fresh memory what I was doing then. I did some simple search and this might be what you are looking for:

- [This line](https://github.com/qobilidop/srcnn/blob/2fefbd6e14275f7a1cc69d52c666b3e09d3b9f35/toolbox/experiment.py#L185) generates the output image.
- [This line](https://github.com/qobilidop/srcnn/blob/2fefbd6e14275f7a1cc69d52c666b3e09d3b9f35/toolbox/experiment.py#L198) and below save the output image.

**Comment by normalworld** [comment]
Thanks

**Comment by normalworld** [comment]
Sorry to bother you.It confuses me that the [post_process function](https://github.com/qobilidop/srcnn/blob/2fefbd6e14275f7a1cc69d52c666b3e09d3b9f35/toolbox/experiment.py#L73) concatenate [y_pred with bicubic_array](https://github.com/qobilidop/srcnn/blob/2fefbd6e14275f7a1cc69d52c666b3e09d3b9f35/toolbox/experiment.py#L184).

**Comment by qobilidop** [comment]
This is because we are only learning on the Y channel in the YCbCr space. In post processing, the predicted Y channel is concatenated with the other two channels from bicubic interpolation to show a normal image. See 4.5 in the [SRCNN](https://arxiv.org/pdf/1501.00092.pdf) paper.
