### ISSUE TITLE
there are something wrong with bicubic results

### ISSUE THREAD

**Issue by xkyi** [qobilidop/srcnn#13]
image have some shifting

**Comment by qobilidop** [comment]
I remember having seen different results of bicubic interpolation between [Tensorflow](https://www.tensorflow.org/api_docs/python/tf/image/ResizeMethod) and [Pillow](http://pillow.readthedocs.io/en/3.0.x/reference/Image.html#PIL.Image.Image.resize). But we didn't have time to look into the details. So we simply adopted the Tensorflow method. This might be related to what you're seeing.
