### ISSUE TITLE
Couldn't find weight file when resume from the 1st epoch

### ISSUE THREAD

**Issue by LoSealL** [qobilidop/srcnn#14]
The last epoch resumed from csv record file is **0** while the index of saved weight file starts from 1.
If resume from the 1st epoch training, there could be a mistake that can't load `ep0000.hdf5`

**Comment by qobilidop** [comment]
Thanks, that's a good catch! I don't plan to maintain this repo anymore, but you're welcome to fork and tune it to your like.
