### ISSUE TITLE
The datasets to use

### ISSUE THREAD

**Issue by qobilidop** [qobilidop/srcnn#2]
Do we use both the 91 image dataset and the ImageNet dataset or only the former one?

**Comment by xiongliyang219** [comment]
I prefer both

**Comment by qobilidop** [comment]
@xiongliyang219 What is the time needed to train on ImageNet compared to the 91 image dataset?

**Comment by xiongliyang219** [comment]
The paper says "The training time on ImageNet is about the same as on the 91-image dataset since the number of backpropagations is the same."

**Comment by qobilidop** [comment]
We decided to use both.
