### ISSUE TITLE
"Deconvolution" layer

### ISSUE THREAD

**Issue by qobilidop** [qobilidop/srcnn#4]
This thread is for the discussion of the "deconvolution" layer. Close it once we finish the discussion in the progress report.

**Comment by xiongliyang219** [comment]
https://arxiv.org/pdf/1608.00367.pdf
> We will then show that for a fixed computational budget and complexity, a network with convolutions exclusively in LR space has more representation power at the same speed than a network that first upsamples the input in HR space.

http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=5539957

http://datascience.stackexchange.com/questions/6107/what-are-deconvolutional-layers

https://arxiv.org/pdf/1609.07009.pdf

**Comment by zfang92** [comment]
http://ieeexplore.ieee.org/abstract/document/489268/

https://www.quora.com/How-do-fully-convolutional-networks-upsample-their-coarse-output

https://www.youtube.com/watch?v=ByjaPdWXKJ4&feature=youtu.be&t=17m00s

http://www.cv-foundation.org/openaccess/content_cvpr_2013/html/Schuler_A_Machine_Learning_2013_CVPR_paper.html

**Comment by qobilidop** [comment]
I've created a [wiki page](https://github.com/qobilidop/srcnn/wiki/Paper-Notes) to keep track of relevant papers. Feel free to edit it.

**Comment by qobilidop** [comment]
Basically, [this note](https://arxiv.org/abs/1609.07009) proved that the deconvolution layer can be replaced by a convolutional layer, and is not as good (less representation power).

**Comment by qobilidop** [comment]
Progress report is submitted.
